# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-07 13:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('el_library', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=2000)),
                ('rating', models.FloatField(default=0)),
                ('type_material', models.CharField(choices=[('Book', 'Книга'), ('Method', 'Методические указания'), ('Method', 'Методические указания')], max_length=1)),
            ],
        ),
    ]
