# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-13 23:16
from __future__ import unicode_literals

from django.db import migrations, models
import tagulous.models.fields
import tagulous.models.models


class Migration(migrations.Migration):

    dependencies = [
        ('el_library', '0002_material'),
    ]

    operations = [
        migrations.CreateModel(
            name='_Tagulous_Material_tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField()),
                ('count', models.IntegerField(default=0, help_text='Internal counter of how many times this tag is in use')),
                ('protected', models.BooleanField(default=False, help_text='Will not be deleted when the count reaches 0')),
            ],
            options={
                'abstract': False,
                'ordering': ('name',),
            },
            bases=(tagulous.models.models.BaseTagModel, models.Model),
        ),
        migrations.AlterField(
            model_name='material',
            name='type_material',
            field=models.CharField(choices=[('Book', 'Книга'), ('Method', 'Методические указания'), ('Ucheb', 'Учебное пособие'), ('Article', 'Статья'), ('Ref', 'Реферта'), ('Esse', 'Эссе'), ('Other', 'Другое')], max_length=1),
        ),
        migrations.AlterUniqueTogether(
            name='_tagulous_material_tags',
            unique_together=set([('slug',)]),
        ),
        migrations.AddField(
            model_name='material',
            name='tags',
            field=tagulous.models.fields.TagField(_set_tag_meta=True, autocomplete_view='material_tag_autocomplete', force_lowercase=True, help_text='Enter a comma-separated tag string', max_count=5, to='el_library._Tagulous_Material_tags'),
        ),
    ]
