# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-13 23:26
from __future__ import unicode_literals

from django.db import migrations
import tagulous.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('el_library', '0003_auto_20170413_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='tags',
            field=tagulous.models.fields.TagField(_set_tag_meta=True, autocomplete_view='material_tag_autocomplete', force_lowercase=True, help_text='This field does not split on spaces', max_count=5, to='el_library._Tagulous_Material_tags'),
        ),
    ]
