# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-13 23:52
from __future__ import unicode_literals

from django.db import migrations, models
import tagulous.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('el_library', '0004_auto_20170413_2326'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='document',
            field=models.FileField(default=0, upload_to=''),
        ),
        migrations.AlterField(
            model_name='material',
            name='tags',
            field=tagulous.models.fields.TagField(_set_tag_meta=True, autocomplete_view='material_tag_autocomplete', force_lowercase=True, help_text='This field does not split on spaces', initial='eating, coding, gaming', max_count=5, to='el_library._Tagulous_Material_tags'),
        ),
    ]
