# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-14 00:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('el_library', '0005_auto_20170413_2352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='type_material',
            field=models.CharField(choices=[('Book', 'Книга'), ('Method', 'Методические указания'), ('Ucheb', 'Учебное пособие'), ('Article', 'Статья'), ('Ref', 'Реферта'), ('Esse', 'Эссе'), ('Other', 'Другое')], max_length=20),
        ),
    ]
