# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-14 00:48
from __future__ import unicode_literals

from django.db import migrations
import tagulous.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('el_library', '0007_auto_20170414_0047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='tags',
        ),
        migrations.AddField(
            model_name='material',
            name='tags',
            field=tagulous.models.fields.TagField(_set_tag_meta=True, autocomplete_view='el_library.views.material_tag_autocomplete', force_lowercase=True, help_text='Enter a comma-separated tag string', initial='eating, coding, gaming', to='el_library.Tags'),
        ),
    ]
