# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-17 16:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('el_library', '0010_auto_20170414_1249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='document',
        ),
    ]
