# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-04-20 23:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('el_library', '0012_material_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rubrik',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('parent_id', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='material',
            name='isbn',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='type_material',
            field=models.CharField(choices=[(b'Book', b'\xd0\x9a\xd0\xbd\xd0\xb8\xd0\xb3\xd0\xb0'), (b'Method', b'\xd0\x9c\xd0\xb5\xd1\x82\xd0\xbe\xd0\xb4\xd0\xb8\xd1\x87\xd0\xb5\xd1\x81\xd0\xba\xd0\xb8\xd0\xb5 \xd1\x83\xd0\xba\xd0\xb0\xd0\xb7\xd0\xb0\xd0\xbd\xd0\xb8\xd1\x8f'), (b'Ucheb', b'\xd0\xa3\xd1\x87\xd0\xb5\xd0\xb1\xd0\xbd\xd0\xbe\xd0\xb5 \xd0\xbf\xd0\xbe\xd1\x81\xd0\xbe\xd0\xb1\xd0\xb8\xd0\xb5'), (b'Article', b'\xd0\xa1\xd1\x82\xd0\xb0\xd1\x82\xd1\x8c\xd1\x8f'), (b'Ref', b'\xd0\xa0\xd0\xb5\xd1\x84\xd0\xb5\xd1\x80\xd1\x82\xd0\xb0'), (b'Esse', b'\xd0\xad\xd1\x81\xd1\x81\xd0\xb5'), (b'Other', b'\xd0\x94\xd1\x80\xd1\x83\xd0\xb3\xd0\xbe\xd0\xb5')], max_length=20),
        ),
        migrations.AddField(
            model_name='material',
            name='rubrik',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='el_library.Rubrik'),
        ),
    ]
