# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-04-21 00:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('el_library', '0013_auto_20170420_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rubrik',
            name='parent_id',
            field=models.IntegerField(null=True),
        ),
    ]
