# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-03 17:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('el_library', '0014_auto_20170421_0059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='avatar',
        ),
        migrations.AddField(
            model_name='material',
            name='is_approved',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='material',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rubrik',
            name='is_approved',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='material',
            name='type_material',
            field=models.CharField(choices=[('Book', 'Книга'), ('Method', 'Методические указания'), ('Ucheb', 'Учебное пособие'), ('Article', 'Статья'), ('Ref', 'Реферта'), ('Esse', 'Эссе'), ('Other', 'Другое')], max_length=20),
        ),
    ]
