# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-03 18:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('el_library', '0017_remove_profile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='is_deleted',
            field=models.IntegerField(default=0),
        ),
    ]
