# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-11 14:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('el_library', '0018_material_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='isbn',
            field=models.BigIntegerField(null=True),
        ),
    ]
