# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-19 09:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('el_library', '0022_material_is_app_changed'),
    ]

    operations = [
        migrations.AddField(
            model_name='tags',
            name='is_deleted',
            field=models.IntegerField(default=0),
        ),
    ]
