# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-22 22:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('el_library', '0024_access'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='el_library.Access'),
        ),
    ]
